import Head from "next/head";

// Components
import WithAuth from "../components/withAuth";
import Layout from "../components/Layout";
import BottomNav from "../components/BottomNav";

// Material UI
import { Avatar, Input, Progress, Text } from "@nextui-org/react";
import { SearchRounded } from "@mui/icons-material";
import {
  List,
  ListItem,
  ListItemAvatar,
  ListItemText,
  Typography,
} from "@mui/material";

// hooks
import usePatients from "../hooks/usePatients";

function History() {
  const { docs, loading, error } = usePatients();

  return (
    <>
      <Head>
        <title>Historial | Boreal </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h2>Historial</h2>
        <Input
          placeholder="Buscar"
          css={{ w: "100%" }}
          contentRight={<SearchRounded />}
          disabled
        />

        {loading ? (
          <Progress
            size="xs"
            indeterminated
            color="primary"
            status="primary"
            css={{ mb: "1rem" }}
          />
        ) : error ? (
          <>
            <Progress
              size="xs"
              indeterminated
              color="primary"
              status="primary"
              css={{ mb: "1rem" }}
            />
            <Text css={{ mb: "1rem" }}>
              Error al cargar el Historial, por favor intentalo mas tarde.
            </Text>
          </>
        ) : docs.length <= 0 ? (
          <Text css={{ mt: "1rem" }}>Aun no hay pacientes agregados.</Text>
        ) : (
          <List
            sx={{
              width: "100%",
              marginTop: "1.5rem",
            }}
          >
            {docs.map((doc) => (
              <ListItem key={doc.id} alignItems="center">
                <ListItemAvatar>
                  <Avatar src={doc.imageDoc} />
                </ListItemAvatar>
                <ListItemText
                  secondary={
                    <>
                      <Typography
                        sx={{ display: "inline" }}
                        component="span"
                        variant="body2"
                        color="text.primary"
                      >
                        {doc.doc}
                      </Typography>
                      {` ha atendido a `}
                      <Typography
                        sx={{ display: "inline" }}
                        component="span"
                        variant="body2"
                        color="text.primary"
                      >
                        {doc.name}.
                      </Typography>
                      {` ${doc.date} - ${doc.time} `}
                    </>
                  }
                />
              </ListItem>
            ))}
          </List>
        )}
      </Layout>
      <BottomNav />
    </>
  );
}
export default WithAuth(History);
