import Head from "next/head";

// Styles
import s from "../styles/Home.module.css";

// Local Components
import BottomNav from "../components/BottomNav";
import WithAuth from "../components/withAuth";
import CardInfo from "../components/CardInfo";
import Layout from "../components/Layout";

// Hooks
import usePatients from "../hooks/usePatients";

// Material UI
import { Collapse, Input, Progress, Text } from "@nextui-org/react";
import { SearchRounded } from "@mui/icons-material";

function Inicio() {
  const { docs, loading, error } = usePatients();

  return (
    <>
      <Layout>
        <Head>
          <title>Home | Boreal </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h2>Recientes</h2>
        <Input
          placeholder="Buscar"
          css={{ w: "100%", mb: "1.5rem" }}
          contentRight={<SearchRounded />}
          disabled
        />
        {loading ? (
          <Progress
            size="xs"
            indeterminated
            color="primary"
            status="primary"
            css={{ mb: "1rem" }}
          />
        ) : error ? (
          <>
            <Progress
              size="xs"
              indeterminated
              color="primary"
              status="primary"
              css={{ mb: "1rem" }}
            />
            <Text css={{ mb: "1rem" }}>
              Error al cargar los pacientes, por favor intentalo mas tarde.
            </Text>
          </>
        ) : docs.length <= 0 ? (
          <Text>Aun no hay pacientes agregados.</Text>
        ) : (
          <div className={s.cardContainer}>
            <Collapse.Group
              accordion={true}
              css={{ mb: "5rem", w: "100%" }}
              shadow
            >
              {docs.map((doc) => (
                <CardInfo
                  key={doc.id}
                  name={doc.name}
                  doc={doc.doc}
                  time={doc.time}
                  date={doc.date}
                  image={doc.image}
                  description={doc.description}
                  pago={doc.pago}
                  metodo={doc.metodo}
                  materials={doc.materials}
                />
              ))}
            </Collapse.Group>
          </div>
        )}
      </Layout>
      <BottomNav />
    </>
  );
}

export default WithAuth(Inicio);
