import React from "react";
import Head from "next/head";
import BottomNav from "../components/BottomNav";
import WithAuth from "../components/withAuth";
import useAuth from "../hooks/useAuth";
import s from "../styles/Home.module.css";
import Layout from "../components/Layout";
import { Button, Card, Grid, Row, Text } from "@nextui-org/react";

function Inicio() {
  const { signOut } = useAuth();

  return (
    <>
      <Layout>
        <Head>
          <title>Home | Boreal </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h2>Hoy</h2>
        <div className={s.cardContainer}>
          <Card css={{ w: "100%" }}>
            <Text h3>Kevin Collazos</Text>
            <p> El procedimiento tal y tal</p>
            <Card.Footer>Dra. Sandra Peña</Card.Footer>
          </Card>
          <Card css={{ w: "100%" }}>
            <Text h3>Kevin Collazos</Text>
            <p> El procedimiento tal y tal</p>
            <Card.Footer>Dra. Sandra Peña</Card.Footer>
          </Card>
        </div>
        <Button variant="contained" color="primary" onClick={signOut}>
          Bye
        </Button>
      </Layout>
      <BottomNav />
    </>
  );
}

export default WithAuth(Inicio);
