import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import s from "../styles/Login.module.css";
import { Button, TextField } from "@mui/material";
import useAuth from "../hooks/useAuth";
import WithAuth from "../components/withAuth";
import Layout from "../components/Layout";

function Home() {
  const [values, setValues] = useState();
  const { signIn } = useAuth();

  const handleInput = (event) => {
    setValues({
      ...values,
      [event.target.name]: event.target.value,
    });
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    signIn(`${values.email}@gmail.com`, values.password);
  };

  return (
    <Layout>
      <Head>
        <title>Login | Boreal </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form className={s.loginContainer} onSubmit={handleSubmit}>
        <Image
          src="/../public/Logo.svg"
          alt="Logo"
          className={s.logo}
          width={250}
          height={250}
        />
        <TextField
          className={s.loginInput}
          label="Correo"
          variant="outlined"
          name="email"
          autoFocus
          onChange={handleInput}
        />
        <TextField
          className={s.loginInput}
          label="Contrase&ntilde;a"
          variant="outlined"
          name="password"
          onChange={handleInput}
        />
        <Button
          className={s.loginButton}
          type="submit"
          variant="contained"
          size="large"
        >
          Ingresar
        </Button>
      </form>
    </Layout>
  );
}

export default WithAuth(Home, {
  isAuthPage: true,
});
