import { useState } from "react";
import Head from "next/head";
import Image from "next/image";

// Styles
import s from "../styles/Login.module.css";

// Hooks
import useAuth from "../hooks/useAuth";

// Local Components
import WithAuth from "../components/withAuth";
import Layout from "../components/Layout";

// Material UI
import { Input, Button } from "@nextui-org/react";

// Icons
import { VisibilityOffRounded, VisibilityRounded } from "@mui/icons-material";

function Home() {
  const [values, setValues] = useState({
    showPassword: false,
  });
  const { signIn } = useAuth();

  const handleInput = (event) => {
    setValues({
      ...values,
      [event.target.name]: event.target.value,
    });
  };

  const handleClickShowPassword = () => {
    setValues({
      ...values,
      showPassword: !values.showPassword,
    });
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    signIn(`${values.email}@gmail.com`, values.password);
  };

  const handleMouseDownPassword = (event) => {
    event.preventDefault();
  };

  return (
    <Layout>
      <Head>
        <title>Login | Boreal </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form className={s.loginContainer} onSubmit={handleSubmit}>
        <Image
          src="/Logo.svg"
          alt="Logo"
          className={s.logo}
          width={250}
          height={250}
          priority
        />
        <Input
          label="Usuario"
          variant="outlined"
          name="email"
          onChange={handleInput}
          css={{ w: "100%", mw: "440px" }}
          size="lg"
        />
        {/* <OutlinedInput
          className={s.loginInput}
          label="Contraseña"
          name="password"
          type={values.showPassword ? "text" : "password"}
          onChange={handleInput}
          endAdornment={
            <InputAdornment position="end">
              <IconButton
                aria-label="toggle password visibility"
                onClick={handleClickShowPassword}
                onMouseDown={handleMouseDownPassword}
                edge="end"
              >
                {values.showPassword ? <VisibilityOff /> : <Visibility />}
              </IconButton>
            </InputAdornment>
          }
        /> */}
        <Input.Password
          label="Contraseña"
          name="password"
          onChange={handleInput}
          visibleIcon={<VisibilityOffRounded />}
          hiddenIcon={<VisibilityRounded />}
          css={{ w: "100%", mw: "440px" }}
          size="lg"
        />
        <Button
          className={s.loginButton}
          css={{ w: "100%", bg: "#000" }}
          type="submit"
        >
          Ingresar
        </Button>
      </form>
    </Layout>
  );
}

export default WithAuth(Home, {
  isAuthPage: true,
});
