import React from "react";
import Head from "next/head";

// Styles
import s from "../components/styles/Profile.module.css";

// Local Components
import BottomNav from "../components/BottomNav";
import WithAuth from "../components/withAuth";
import Layout from "../components/Layout";

// Hooks
import useAuth from "../hooks/useAuth";

// Material UI
import { Avatar, Button, Divider } from "@nextui-org/react";

function Profile() {
  const { userData, signOut } = useAuth();

  return (
    <>
      <Head>
        <title>Profile | Boreal </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h2>Perfil</h2>
        <div className={s.userInfoContainer}>
          <Avatar squared css={{ w: 100, h: 100 }} src="/Octocat.jpg" />
          <h3>{userData.name}</h3>
        </div>
        <Divider css={{ mb: "1rem" }} />
        <Button.Group size="lg" vertical auto css={{ w: "100%" }}>
          <Button css={{ bg: "#000", color: "#fff" }}>Pacientes</Button>
          <Button css={{ bg: "#000", color: "#fff" }} onClick={signOut}>
            Cerrar sesión
          </Button>
        </Button.Group>
      </Layout>
      <BottomNav />
    </>
  );
}

export default WithAuth(Profile);
