import React from "react";
import Head from "next/head";
import BottomNav from "../components/BottomNav";
import WithAuth from "../components/withAuth";
import Layout from "../components/Layout";

function profile() {
  return (
    <>
      <Head>
        <title>Profile | Boreal </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Perfil</h1>
      </Layout>
      <BottomNav />
    </>
  );
}

export default WithAuth(profile);
